/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChairmanRouteImport } from './routes/chairman'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenturesIndexRouteImport } from './routes/ventures/index'
import { Route as VenturesSlugRouteImport } from './routes/ventures/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairmanRoute = ChairmanRouteImport.update({
  id: '/chairman',
  path: '/chairman',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesIndexRoute = VenturesIndexRouteImport.update({
  id: '/ventures/',
  path: '/ventures/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesSlugRoute = VenturesSlugRouteImport.update({
  id: '/ventures/$slug',
  path: '/ventures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/chairman': typeof ChairmanRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/ventures/': typeof VenturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/chairman': typeof ChairmanRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/ventures': typeof VenturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/chairman': typeof ChairmanRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/ventures/': typeof VenturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amenities'
    | '/chairman'
    | '/contact'
    | '/gallery'
    | '/sitemap.xml'
    | '/ventures/$slug'
    | '/ventures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/chairman'
    | '/contact'
    | '/gallery'
    | '/sitemap.xml'
    | '/ventures/$slug'
    | '/ventures'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amenities'
    | '/chairman'
    | '/contact'
    | '/gallery'
    | '/sitemap.xml'
    | '/ventures/$slug'
    | '/ventures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ChairmanRoute: typeof ChairmanRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenturesSlugRoute: typeof VenturesSlugRoute
  VenturesIndexRoute: typeof VenturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairman': {
      id: '/chairman'
      path: '/chairman'
      fullPath: '/chairman'
      preLoaderRoute: typeof ChairmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/': {
      id: '/ventures/'
      path: '/ventures'
      fullPath: '/ventures/'
      preLoaderRoute: typeof VenturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/$slug': {
      id: '/ventures/$slug'
      path: '/ventures/$slug'
      fullPath: '/ventures/$slug'
      preLoaderRoute: typeof VenturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmenitiesRoute: AmenitiesRoute,
  ChairmanRoute: ChairmanRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenturesSlugRoute: VenturesSlugRoute,
  VenturesIndexRoute: VenturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
